# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npeer.proto\"\x1f\n\x0flistFilesSended\x12\x0c\n\x04\x66ile\x18\x01 \x03(\t\"#\n\x0c\x63onfirmation\x12\x13\n\x0bstatus_code\x18\x01 \x01(\t2E\n\rServerHandler\x12\x34\n\x0fpoll_peer_files\x12\x10.listFilesSended\x1a\r.confirmation\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'peer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LISTFILESSENDED']._serialized_start=14
  _globals['_LISTFILESSENDED']._serialized_end=45
  _globals['_CONFIRMATION']._serialized_start=47
  _globals['_CONFIRMATION']._serialized_end=82
  _globals['_SERVERHANDLER']._serialized_start=84
  _globals['_SERVERHANDLER']._serialized_end=153
# @@protoc_insertion_point(module_scope)
